### ISSUE TITLE
[Issue] OSError: CUDA_HOME environment variable is not set

### ISSUE THREAD

**Issue by Julien-Gustin** [montefiore-ai/alan-cluster#58]
**Describe the issue**
I try to install and build the following source code [PoinTr](https://github.com/yuxumin/PoinTr) but when I run the command `bash install.sh` as requested I get the following error:

`OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root`

The full error is 

```(PoinTR) [jgustin@master chamfer_dist]$ python setup.py install --user
Traceback (most recent call last):
  File "/home/jgustin/PoinTr/extensions/chamfer_dist/setup.py", line 14, in <module>
    CUDAExtension('chamfer', [
  File "/home/jgustin/anaconda3/envs/PoinTR/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1047, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/jgustin/anaconda3/envs/PoinTR/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1179, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/jgustin/anaconda3/envs/PoinTR/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2230, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
```

**To Reproduce**
1. `conda create -n PoinTr`
2. `conda activate PoinTr`
3. `git clone https://github.com/yuxumin/PoinTr.git`
4. `pip install -r requirements.txt`
4b. `conda install pytorch torchvision cudatoolkit=11.7 -c pytorch -c conda-forge` (I tried with and without this command as it is not directly requested in the requirement.)
5. `bash install.sh`

**Expected behavior**
That the installation works successfully, below is an example of the expected output after the installations using google colab:

```
/content/gdrive/MyDrive/Informatique ULG/TFE/PoinTr/extensions/chamfer_dist
running install
running bdist_egg
running egg_info
creating chamfer.egg-info
writing chamfer.egg-info/PKG-INFO
writing dependency_links to chamfer.egg-info/dependency_links.txt
writing top-level names to chamfer.egg-info/top_level.txt
writing manifest file 'chamfer.egg-info/SOURCES.txt'
/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:411: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
writing manifest file 'chamfer.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py:813: UserWarning: The detected CUDA version (11.2) has a minor version mismatch with the version that was used to compile PyTorch (11.3). Most likely this shouldn't be a problem.
  warnings.warn(CUDA_MISMATCH_WARN.format(cuda_str_version, torch.version.cuda))
building 'chamfer' extension
creating build
creating build/temp.linux-x86_64-3.8
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.8/dist-packages/torch/include -I/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.8/dist-packages/torch/include/TH -I/usr/local/lib/python3.8/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.8 -c chamfer_cuda.cpp -o build/temp.linux-x86_64-3.8/chamfer_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/usr/local/cuda/bin/nvcc -I/usr/local/lib/python3.8/dist-packages/torch/include -I/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.8/dist-packages/torch/include/TH -I/usr/local/lib/python3.8/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.8 -c chamfer.cu -o build/temp.linux-x86_64-3.8/chamfer.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE="_gcc" -DPYBIND11_STDLIB="_libstdcpp" -DPYBIND11_BUILD_ABI="_cxxabi1011" -DTORCH_EXTENSION_NAME=chamfer -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 -std=c++14
/usr/local/lib/python3.8/dist-packages/torch/include/c10/core/SymInt.h(84): warning: integer conversion resulted in a change of sign

/usr/local/lib/python3.8/dist-packages/torch/include/c10/core/SymInt.h(84): warning: integer conversion resulted in a change of sign

creating build/lib.linux-x86_64-3.8
x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -g -fwrapv -O2 -Wl,-Bsymbolic-functions -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.8/chamfer_cuda.o build/temp.linux-x86_64-3.8/chamfer.o -L/usr/local/lib/python3.8/dist-packages/torch/lib -L/usr/local/cuda/lib64 -lc10 -ltorch -ltorch_cpu -ltorch_python -lcudart -lc10_cuda -ltorch_cuda_cu -ltorch_cuda_cpp -o build/lib.linux-x86_64-3.8/chamfer.cpython-38-x86_64-linux-gnu.so
creating build/bdist.linux-x86_64
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.8/chamfer.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for chamfer.cpython-38-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/chamfer.py to chamfer.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying chamfer.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying chamfer.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying chamfer.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying chamfer.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.chamfer.cpython-38: module references __file__
creating dist
creating 'dist/chamfer-2.0.0-py3.8-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing chamfer-2.0.0-py3.8-linux-x86_64.egg
creating /root/.local/lib/python3.8/site-packages/chamfer-2.0.0-py3.8-linux-x86_64.egg
Extracting chamfer-2.0.0-py3.8-linux-x86_64.egg to /root/.local/lib/python3.8/site-packages
Adding chamfer 2.0.0 to easy-install.pth file

Installed /root/.local/lib/python3.8/site-packages/chamfer-2.0.0-py3.8-linux-x86_64.egg
Processing dependencies for chamfer==2.0.0
Finished processing dependencies for chamfer==2.0.0
```

**Comment by glouppe** [comment]
What version of `cudatoolkit` have you installed in your conda env?

**Comment by Julien-Gustin** [comment]
I have installed version 11.7.0. I don't know if it's normal but the `nvcc` and `nvidia-smi` commands don't work.
```
(PoinTR) [jgustin@master train]$ nvcc --version
-bash: nvcc: command not found

(PoinTR) [jgustin@master train]$ nvidia-smi
-bash: nvidia-smi: command not found

(PoinTR) [jgustin@master train]$ conda list cudatoolkit
# packages in environment at /home/jgustin/anaconda3/envs/PoinTR:
#
# Name                    Version                   Build  Channel
cudatoolkit               11.7.0              hd8887f6_10    conda-forge
```
